# Generated by Django 4.0.4 on 2022-07-07 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('background', models.ImageField(upload_to='')),
                ('icon', models.ImageField(upload_to='')),
                ('importance', models.TextField()),
                ('advantages', models.TextField()),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('feedback', models.TextField()),
                ('advice', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student_page',
            },
        ),
        migrations.CreateModel(
            name='PageDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.CharField(max_length=255)),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.feature')),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_pages', to='page.page')),
                ('referenced_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refernced_pages', to='page.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='dependencies',
            field=models.ManyToManyField(through='page.PageDependency', to='page.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='students',
            field=models.ManyToManyField(through='page.StudentPage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='tools',
            field=models.ManyToManyField(to='page.tool'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page'),
        ),
    ]
