# Generated by Django 4.0.4 on 2022-07-07 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedependency',
            name='referenced_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_pages', to='page.page'),
        ),
    ]
