# Generated by Django 4.0.4 on 2022-07-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_pagedependency_referenced_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentpage',
            options={},
        ),
        migrations.AlterField(
            model_name='page',
            name='tools',
            field=models.ManyToManyField(db_table='page_tools', to='page.tool'),
        ),
        migrations.AlterModelTable(
            name='page',
            table='page',
        ),
        migrations.AlterModelTable(
            name='pagedependency',
            table='page_depenency',
        ),
        migrations.AlterModelTable(
            name='studentpage',
            table='student_page',
        ),
    ]
