# Generated by Django 4.0.4 on 2022-07-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_page_options_alter_studentpage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PageReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('index', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'page_reference',
            },
        ),
        migrations.RenameField(
            model_name='page',
            old_name='advantages',
            new_name='advice_and_tools',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='importance',
            new_name='importance_and_advantages',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='description',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='page',
        ),
        migrations.RemoveField(
            model_name='page',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='pagedependency',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='pagedependency',
            name='feature_value',
        ),
        migrations.RemoveField(
            model_name='pagedependency',
            name='referenced_page',
        ),
        migrations.RemoveField(
            model_name='studentpage',
            name='advice',
        ),
        migrations.RemoveField(
            model_name='studentpage',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='studentpage',
            name='status',
        ),
        migrations.AddField(
            model_name='feature',
            name='value',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='references',
            field=models.ManyToManyField(related_name='reference_set', through='page.PageReference', to='page.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='view_template',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pagedependency',
            name='dependant_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependant_pages', to='page.page'),
        ),
        migrations.AddField(
            model_name='studentpage',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='dependencies',
            field=models.ManyToManyField(related_name='dependency_set', through='page.PageDependency', to='page.page'),
        ),
        migrations.AlterField(
            model_name='pagedependency',
            name='parent_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_dependencies', to='page.page'),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.AddField(
            model_name='pagereference',
            name='parent_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_references', to='page.page'),
        ),
        migrations.AddField(
            model_name='pagereference',
            name='referenced_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_pages', to='page.page'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page'),
        ),
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.page'),
        ),
        migrations.AddField(
            model_name='feature',
            name='page_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.pagereference'),
        ),
    ]
