# Generated by Django 4.0.4 on 2022-07-07 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rate',
            },
        ),
        migrations.CreateModel(
            name='RatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.rate')),
            ],
            options={
                'db_table': 'rated_item',
            },
        ),
    ]
