# Generated by Django 4.0.4 on 2022-07-07 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv', '0002_rename_user_id_contact_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='study_year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projects',
        ),
        migrations.AddField(
            model_name='experience',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_graduated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_cerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='cv.Membership', to='cv.profile', verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('mark', models.PositiveIntegerField()),
                ('data', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
